- name: Install VisualStudio code
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Download Microsoft key
      get_url: url=https://packages.microsoft.com/keys/microsoft.asc dest=/tmp/microsoft.asc

    - name: Dearmor key
      command: gpg -o /tmp/microsoft.gpg --dearmor /tmp/microsoft.asc
      become: True

    - name: Add microsoft key in apt
      apt_key: file=/tmp/microsoft.gpg
      become: True

    - name: Add VSCode apt repo
      apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main' update_cache=yes
      become: True

    - name: Install VS Code
      apt: name=code
      become: True

        
