- name: Install Chrome
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Google Chrome key
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub
      become: yes

    - name: Add Google Chrome repo
      apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" update_cache=yes
      become: yes

    - name: Install Google Chrome
      apt: pkg=google-chrome-stable
      become: yes
