- name: Install Virtual Box
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Virtual Box key
      apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc
      become: True

    - name: Add Virtual Box repository
      apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian xenial contrib' update_cache=yes
      become: True
    
    - name: Install Virtual Box
      apt: name=virtualbox-5.1
      become: True