- name: Install needed packages on all my machine
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      become_method: sudo 
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - htop
        - jq
        - python3-pip
        - python3-virtualenv
        - tmux
        - xclip
        
