- name: Install nvim
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add nvim apt repo
      apt_repository: repo='ppa:neovim-ppa/stable' update_cache=yes
      become: True

    - name: Install nvim
      apt: name=neovim
      become: True

    #- name: Setup vim config

    - name: Setup alternatives
      shell: |
        update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
        update-alternatives --config vi
        update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
        update-alternatives --config vim
        update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
        update-alternatives --config editor
      become: True


        
